FROM gradle:4.8-jdk8 as builder

COPY . /usr/src/gateway
USER root
RUN chown -R gradle:gradle /usr/src/gateway
USER gradle
WORKDIR /usr/src/gateway

RUN gradle build

FROM adoptopenjdk/openjdk8-openj9:alpine-slim
COPY --from=builder /usr/src/gateway/build/libs/restaurant-gateway-0.0.1.jar gateway.jar

CMD java $JAVA_OPTS -Xshareclasses -Xquickstart -jar /gateway.jar
EXPOSE 8080