apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    hostname: "*.restaurant.io"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All