apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: catalog-api
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /catalog
    backendRefs:
    - name: catalog-api
      port: 80