apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        image: identity-api
        envFrom:
          - configMapRef:
              name: identity-api
          - secretRef:
              name: identity-api
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 5
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 5
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 80
        #   initialDelaySeconds: 10
        #   periodSeconds: 15
        #   successThreshold: 1
        #   failureThreshold: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
