apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- order-pgsql.yaml
- http-route.yaml

configMapGenerator:
- envs:
  - config.env
  name: order-api

secretGenerator:
- name: order-api
  envs: [".env.secret"]

images:
- name: order-api
  newName: ghcr.io/chayxana/order
  newTag: 1.0.1
