---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
  labels: 
    app: dashboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      containers:
      - image: jurabek/dashboard
        imagePullPolicy: IfNotPresent
        name: dashboard-app
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "60m"
          limits:
            memory: "64Mi"
            cpu: "100m"

---
        
---
