apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- http-route.yaml

configMapGenerator:
- envs:
  - config.env
  name: checkout-api

images:
- name: checkout-api
  newName: ghcr.io/chayxana/checkout-api
  newTag: 0.0.7
