apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - datasource.yaml=grafana-datasources.yaml
  name: grafana-datasource-config

resources:
  - "namespace.yaml"
  - "tempo.yaml"
  - "otel-collector.yaml"
  - "grafana.yaml"
  - "jaeger.yaml"
  - "prometheus.yaml"
  - "zipkin.yaml"