apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true

resources:
  - "namespace.yaml"
  - "tempo.yaml"
  - "otel-collector.yaml"
  - "grafana.yaml"