apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel 
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      otlp:
        endpoint: tempo-tempostack-distributor.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

      logging:
        loglevel: debug


      otlphttp:
        endpoint: "https://collector.gethelios.dev"
        traces_endpoint: "https://collector.gethelios.dev/v1/traces"
        headers:
          Authorization: ${env:HS_API_TOKEN}

    processors:
      batch:

      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: container
          - action: insert
            key: loki.format
            value: raw

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, otlphttp]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-traces
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: tracegen
          image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
          env:
            - name: ENDPOINT
              value: otel-collector.monitoring.svc.cluster.local:4317