apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- http_route_patch.yaml

configMapGenerator:
- name: basket-api
  envs: [config.env]
  behavior: merge