apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "cart-api/dev"
  - "catalog-api/dev"
  - "checkout-api/dev"
  - "identity-api/dev"
  - "order-api/dev"
  - "payment-api/dev"