apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

generatorOptions:
  disableNameSuffixHash: true

resources:
  - kafka-stateful-set.yaml
  - service.yaml
  - namespace.yaml
  - pvc.yaml
  - kafka-ui.yaml
  - init-topics-job.yaml

configMapGenerator:
- envs:
  - config.env
  name: kafka-broker-config