apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- redis.yaml
- http-route.yaml

configMapGenerator:
- envs:
  - config.env
  name: basket-api

images:
- name: basket-api
  newName: basket
  newTag: 0.0.9
