name: "Building gradle"
description: "Builds gradle application within the given folder"
inputs:
  service-name: 
    description: 'Service name'
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.service-name }}
        ./gradlew clean
        ./gradlew build
        ./gradlew test jacocoTestReport
      shell: bash