FROM gradle:4.8-jdk8 as builder

COPY . /usr/src/ordering_api
USER root
RUN chown -R gradle:gradle /usr/src/ordering_api
USER gradle

WORKDIR /usr/src/ordering_api
RUN gradle build

FROM openjdk:8-jre-alpine
WORKDIR /root/
COPY --from=builder /usr/src/ordering_api/build/libs/order.api.jar .

EXPOSE 8090
CMD ["java", "-jar", "./order.api.jar"]