namespace Menu.API.Providers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Menu.API.Models;

    public class CurrencyProvider : ICurrencyProvider
    {
        static readonly List<Currency> _currencies = new List<Currency>
        {
            new Currency { Code = "AED", Name = "United Arab Emirates Dirham" },
            new Currency { Code = "AFN", Name = "Afghanistan Afghani" },
            new Currency { Code = "ALL", Name = "Albania Lek" },
            new Currency { Code = "AMD", Name = "Armenia Dram" },
            new Currency { Code = "ANG", Name = "Netherlands Antilles Guilder" },
            new Currency { Code = "AOA", Name = "Angola Kwanza" },
            new Currency { Code = "ARS", Name = "Argentina Peso" },
            new Currency { Code = "AUD", Name = "Australia Dollar" },
            new Currency { Code = "AWG", Name = "Aruba Guilder" },
            new Currency { Code = "AZN", Name = "Azerbaijan New Manat" },
            new Currency { Code = "BAM", Name = "Bosnia and Herzegovina Convertible Marka" },
            new Currency { Code = "BBD", Name = "Barbados Dollar" },
            new Currency { Code = "BDT", Name = "Bangladesh Taka" },
            new Currency { Code = "BGN", Name = "Bulgaria Lev" },
            new Currency { Code = "BHD", Name = "Bahrain Dinar" },
            new Currency { Code = "BIF", Name = "Burundi Franc" },
            new Currency { Code = "BMD", Name = "Bermuda Dollar" },
            new Currency { Code = "BND", Name = "Brunei Darussalam Dollar" },
            new Currency { Code = "BOB", Name = "Bolivia Boliviano" },
            new Currency { Code = "BRL", Name = "Brazil Real" },
            new Currency { Code = "BSD", Name = "Bahamas Dollar" },
            new Currency { Code = "BTN", Name = "Bhutan Ngultrum" },
            new Currency { Code = "BWP", Name = "Botswana Pula" },
            new Currency { Code = "BYR", Name = "Belarus Ruble" },
            new Currency { Code = "BZD", Name = "Belize Dollar" },
            new Currency { Code = "CAD", Name = "Canada Dollar" },
            new Currency { Code = "CDF", Name = "Congo/Kinshasa Franc" },
            new Currency { Code = "CHF", Name = "Switzerland Franc" },
            new Currency { Code = "CLP", Name = "Chile Peso" },
            new Currency { Code = "CNY", Name = "China Yuan Renminbi" },
            new Currency { Code = "COP", Name = "Colombia Peso" },
            new Currency { Code = "CRC", Name = "Costa Rica Colon" },
            new Currency { Code = "CUC", Name = "Cuba Convertible Peso" },
            new Currency { Code = "CUP", Name = "Cuba Peso" },
            new Currency { Code = "CVE", Name = "Cape Verde Escudo" },
            new Currency { Code = "CZK", Name = "Czech Republic Koruna" },
            new Currency { Code = "DJF", Name = "Djibouti Franc" },
            new Currency { Code = "DKK", Name = "Denmark Krone" },
            new Currency { Code = "DOP", Name = "Dominican Republic Peso" },
            new Currency { Code = "DZD", Name = "Algeria Dinar" },
            new Currency { Code = "EGP", Name = "Egypt Pound" },
            new Currency { Code = "ERN", Name = "Eritrea Nakfa" },
            new Currency { Code = "ETB", Name = "Ethiopia Birr" },
            new Currency { Code = "EUR", Name = "Euro Member Countries" },
            new Currency { Code = "FJD", Name = "Fiji Dollar" },
            new Currency { Code = "FKP", Name = "Falkland Islands (Malvinas) Pound" },
            new Currency { Code = "GBP", Name = "United Kingdom Pound" },
            new Currency { Code = "GEL", Name = "Georgia Lari" },
            new Currency { Code = "GGP", Name = "Guernsey Pound" },
            new Currency { Code = "GHS", Name = "Ghana Cedi" },
            new Currency { Code = "GIP", Name = "Gibraltar Pound" },
            new Currency { Code = "GMD", Name = "Gambia Dalasi" },
            new Currency { Code = "GNF", Name = "Guinea Franc" },
            new Currency { Code = "GTQ", Name = "Guatemala Quetzal" },
            new Currency { Code = "GYD", Name = "Guyana Dollar" },
            new Currency { Code = "HKD", Name = "Hong Kong Dollar" },
            new Currency { Code = "HNL", Name = "Honduras Lempira" },
            new Currency { Code = "HRK", Name = "Croatia Kuna" },
            new Currency { Code = "HTG", Name = "Haiti Gourde" },
            new Currency { Code = "HUF", Name = "Hungary Forint" },
            new Currency { Code = "IDR", Name = "Indonesia Rupiah" },
            new Currency { Code = "ILS", Name = "Israel Shekel" },
            new Currency { Code = "IMP", Name = "Isle of Man Pound" },
            new Currency { Code = "INR", Name = "India Rupee" },
            new Currency { Code = "IQD", Name = "Iraq Dinar" },
            new Currency { Code = "IRR", Name = "Iran Rial" },
            new Currency { Code = "ISK", Name = "Iceland Krona" },
            new Currency { Code = "JEP", Name = "Jersey Pound" },
            new Currency { Code = "JMD", Name = "Jamaica Dollar" },
            new Currency { Code = "JOD", Name = "Jordan Dinar" },
            new Currency { Code = "JPY", Name = "Japan Yen" },
            new Currency { Code = "KES", Name = "Kenya Shilling" },
            new Currency { Code = "KGS", Name = "Kyrgyzstan Som" },
            new Currency { Code = "KHR", Name = "Cambodia Riel" },
            new Currency { Code = "KMF", Name = "Comoros Franc" },
            new Currency { Code = "KPW", Name = "Korea (North) Won" },
            new Currency { Code = "KRW", Name = "Korea (South) Won" },
            new Currency { Code = "KWD", Name = "Kuwait Dinar" },
            new Currency { Code = "KYD", Name = "Cayman Islands Dollar" },
            new Currency { Code = "KZT", Name = "Kazakhstan Tenge" },
            new Currency { Code = "LAK", Name = "Laos Kip" },
            new Currency { Code = "LBP", Name = "Lebanon Pound" },
            new Currency { Code = "LKR", Name = "Sri Lanka Rupee" },
            new Currency { Code = "LRD", Name = "Liberia Dollar" },
            new Currency { Code = "LSL", Name = "Lesotho Loti" },
            new Currency { Code = "LYD", Name = "Libya Dinar" },
            new Currency { Code = "MAD", Name = "Morocco Dirham" },
            new Currency { Code = "MDL", Name = "Moldova Leu" },
            new Currency { Code = "MGA", Name = "Madagascar Ariary" },
            new Currency { Code = "MKD", Name = "Macedonia Denar" },
            new Currency { Code = "MMK", Name = "Myanmar (Burma) Kyat" },
            new Currency { Code = "MNT", Name = "Mongolia Tughrik" },
            new Currency { Code = "MOP", Name = "Macau Pataca" },
            new Currency { Code = "MRO", Name = "Mauritania Ouguiya" },
            new Currency { Code = "MUR", Name = "Mauritius Rupee" },
            new Currency { Code = "MVR", Name = "Maldives (Maldive Islands) Rufiyaa" },
            new Currency { Code = "MWK", Name = "Malawi Kwacha" },
            new Currency { Code = "MXN", Name = "Mexico Peso" },
            new Currency { Code = "MYR", Name = "Malaysia Ringgit" },
            new Currency { Code = "MZN", Name = "Mozambique Metical" },
            new Currency { Code = "NAD", Name = "Namibia Dollar" },
            new Currency { Code = "NGN", Name = "Nigeria Naira" },
            new Currency { Code = "NIO", Name = "Nicaragua Cordoba" },
            new Currency { Code = "NOK", Name = "Norway Krone" },
            new Currency { Code = "NPR", Name = "Nepal Rupee" },
            new Currency { Code = "NZD", Name = "New Zealand Dollar" },
            new Currency { Code = "OMR", Name = "Oman Rial" },
            new Currency { Code = "PAB", Name = "Panama Balboa" },
            new Currency { Code = "PEN", Name = "Peru Nuevo Sol" },
            new Currency { Code = "PGK", Name = "Papua New Guinea Kina" },
            new Currency { Code = "PHP", Name = "Philippines Peso" },
            new Currency { Code = "PKR", Name = "Pakistan Rupee" },
            new Currency { Code = "PLN", Name = "Poland Zloty" },
            new Currency { Code = "PYG", Name = "Paraguay Guarani" },
            new Currency { Code = "QAR", Name = "Qatar Riyal" },
            new Currency { Code = "RON", Name = "Romania New Leu" },
            new Currency { Code = "RSD", Name = "Serbia Dinar" },
            new Currency { Code = "RUB", Name = "Russia Ruble" },
            new Currency { Code = "RWF", Name = "Rwanda Franc" },
            new Currency { Code = "SAR", Name = "Saudi Arabia Riyal" },
            new Currency { Code = "SBD", Name = "Solomon Islands Dollar" },
            new Currency { Code = "SCR", Name = "Seychelles Rupee" },
            new Currency { Code = "SDG", Name = "Sudan Pound" },
            new Currency { Code = "SEK", Name = "Sweden Krona" },
            new Currency { Code = "SGD", Name = "Singapore Dollar" },
            new Currency { Code = "SHP", Name = "Saint Helena Pound" },
            new Currency { Code = "SLL", Name = "Sierra Leone Leone" },
            new Currency { Code = "SOS", Name = "Somalia Shilling" },
            new Currency { Code = "SPL", Name = "Seborga Luigino" },
            new Currency { Code = "SRD", Name = "Suriname Dollar" },
            new Currency { Code = "STD", Name = "São Tomé and Príncipe Dobra" },
            new Currency { Code = "SVC", Name = "El Salvador Colon" },
            new Currency { Code = "SYP", Name = "Syria Pound" },
            new Currency { Code = "SZL", Name = "Swaziland Lilangeni" },
            new Currency { Code = "THB", Name = "Thailand Baht" },
            new Currency { Code = "TJS", Name = "Tajikistan Somoni" },
            new Currency { Code = "TMT", Name = "Turkmenistan Manat" },
            new Currency { Code = "TND", Name = "Tunisia Dinar" },
            new Currency { Code = "TOP", Name = "Tonga Pa'anga" },
            new Currency { Code = "TRY", Name = "Turkey Lira" },
            new Currency { Code = "TTD", Name = "Trinidad and Tobago Dollar" },
            new Currency { Code = "TVD", Name = "Tuvalu Dollar" },
            new Currency { Code = "TWD", Name = "Taiwan New Dollar" },
            new Currency { Code = "TZS", Name = "Tanzania Shilling" },
            new Currency { Code = "UAH", Name = "Ukraine Hryvnia" },
            new Currency { Code = "UGX", Name = "Uganda Shilling" },
            new Currency { Code = "USD", Name = "United States Dollar" },
            new Currency { Code = "UYU", Name = "Uruguay Peso" },
            new Currency { Code = "UZS", Name = "Uzbekistan Som" },
            new Currency { Code = "VEF", Name = "Venezuela Bolivar" },
            new Currency { Code = "VND", Name = "Viet Nam Dong" },
            new Currency { Code = "VUV", Name = "Vanuatu Vatu" },
            new Currency { Code = "WST", Name = "Samoa Tala" },
            new Currency { Code = "XAF", Name = "Communauté Financière Africaine (BEAC) CFA Franc BEAC" },
            new Currency { Code = "XCD", Name = "East Caribbean Dollar" },
            new Currency { Code = "XDR", Name = "International Monetary Fund (IMF) Special Drawing Rights" },
            new Currency { Code = "XOF", Name = "Communauté Financière Africaine (BCEAO) Franc" },
            new Currency { Code = "XPF", Name = "Comptoirs Français du Pacifique (CFP) Franc" },
            new Currency { Code = "YER", Name = "Yemen Rial" },
            new Currency { Code = "ZAR", Name = "South Africa Rand" },
            new Currency { Code = "ZMW", Name = "Zambia Kwacha" },
            new Currency { Code = "ZWD", Name = "Zimbabwe Dollar" }
        };

        public IReadOnlyList<Currency> GetAll()
        {
            return _currencies;
        }

        public Currency GetByCode(string code)
        {
            return _currencies.FirstOrDefault(x => x.Code.Equals(code, StringComparison.OrdinalIgnoreCase));
        }
    }
}