name: "Building maven"
description: "Builds maven application within the given folder"
inputs:
  service-name: 
    description: 'Service name'
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.service-name }}
        ./mvnw install -DskipTests
      shell: bash