definitions:
  models.Cart:
    properties:
      currency:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/models.LineItem'
        type: array
      status:
        type: string
      total:
        type: number
      user_id:
        type: string
    type: object
  models.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.LineItem:
    properties:
      attributes:
        additionalProperties: true
        type: object
      img:
        type: string
      item_id:
        type: integer
      product_description:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
      unit_price:
        type: number
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a rest api for cart which saves items to redis server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cart API
  version: "1.0"
paths:
  /items:
    post:
      consumes:
      - application/json
      description: add by json new CustomerBasket
      parameters:
      - description: Add CustomerBasket
        in: body
        name: CustomerBasket
        required: true
        schema:
          $ref: '#/definitions/models.Cart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Add a CustomerBasket
      tags:
      - CustomerBasket
  /items/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes CustomerBasket by ID
      parameters:
      - description: CustomerBasket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Deletes a CustomerBasket
      tags:
      - CustomerBasket
    get:
      consumes:
      - application/json
      description: Get CustomerBasket by ID
      parameters:
      - description: CustomerBasket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Gets a CustomerBasket
      tags:
      - CustomerBasket
swagger: "2.0"
