definitions:
  models.Address:
    properties:
      city:
        type: string
      country:
        type: string
      state:
        type: string
      street_address:
        type: string
      zip_code:
        type: integer
    type: object
  models.BasketItem:
    properties:
      food_id:
        type: integer
      food_name:
        type: string
      old_unit_price:
        type: number
      picture:
        type: string
      quantity:
        type: integer
      unit_price:
        type: number
    type: object
  models.Checkout:
    properties:
      address:
        $ref: '#/definitions/models.Address'
      credit_card:
        $ref: '#/definitions/models.CreditCardInfo'
      customer_id:
        type: string
      email:
        type: string
      user_currency:
        type: string
    type: object
  models.CreditCardInfo:
    properties:
      credit_card_cvv:
        type: integer
      credit_card_expiration_month:
        type: integer
      credit_card_expiration_year:
        type: integer
      credit_card_number:
        type: string
    type: object
  models.CustomerBasket:
    properties:
      customer_id:
        type: string
      items:
        items:
          $ref: '#/definitions/models.BasketItem'
        type: array
    type: object
  models.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a rest api for basket which saves items to redis server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Basket API
  version: "1.0"
paths:
  /checkout:
    post:
      consumes:
      - application/json
      description: Start checkout
      parameters:
      - description: Checkout
        in: body
        name: Checkout
        required: true
        schema:
          $ref: '#/definitions/models.Checkout'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Starts checkout for the entered card and basket items
      tags:
      - Checkout
  /items:
    post:
      consumes:
      - application/json
      description: add by json new CustomerBasket
      parameters:
      - description: Add CustomerBasket
        in: body
        name: CustomerBasket
        required: true
        schema:
          $ref: '#/definitions/models.CustomerBasket'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CustomerBasket'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Add a CustomerBasket
      tags:
      - CustomerBasket
  /items/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes CustomerBasket by ID
      parameters:
      - description: CustomerBasket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Deletes a CustomerBasket
      tags:
      - CustomerBasket
    get:
      consumes:
      - application/json
      description: Get CustomerBasket by ID
      parameters:
      - description: CustomerBasket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CustomerBasket'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Gets a CustomerBasket
      tags:
      - CustomerBasket
swagger: "2.0"
