import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-gray-100 ">
      <body className={inter.className}>
        <div className="flex">
          <NavBar />
          <div className="flex-grow">
            <Suspense>
              <main>{children}</main>
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  );
}
