FROM gradle:4.8-jdk8 as builder

COPY . /usr/src/gateway
USER root
RUN chown -R gradle:gradle /usr/src/gateway
USER gradle
WORKDIR /usr/src/gateway

RUN gradle build

FROM openjdk:8-jre-alpine
COPY --from=builder /usr/src/gateway/build/libs/restaurant-gateway-0.0.1.jar gateway.jar

ENTRYPOINT ["java", "-jar", "/gateway.jar"]
EXPOSE 8080