FROM gradle:4.8-jdk8 as builder

COPY . /usr/src/discovery
USER root
RUN chown -R gradle:gradle /usr/src/discovery
USER gradle
WORKDIR /usr/src/discovery

RUN gradle build

FROM openjdk:8-jre-alpine
COPY --from=builder /usr/src/discovery/build/libs/restaurant-service-discovery-0.0.1-SNAPSHOT.jar service-discovery.jar
ENTRYPOINT ["java", "-jar", "/service-discovery.jar"]
EXPOSE 8761